### ISSUE TITLE
Expansion Panel contents stray outside borders

### ISSUE THREAD

**Issue by drewhoener** [drewhoener/320-mockup#9]
# What happens
On mobile or in mobile simulator of dev tools, if you go to the My Reviews page and open an expansion panel, the contents stray outside the normal viewport making you scroll left and right to view all content

# What should happen
Content should flex in a vertical manner to allow for better viewing without the need for scrolling left/right

## Reproduction
At commit fe1180cb5f9902a9ee5ecd098190e2068c0669ce
* Start up the frontend and backend servers.
* Open chrome/firefox dev tools and turn on mobile view
* Navigate to my reviews and open an expansion panel
* Content should flow past the right side of the page

**Comment by atnguy** [comment]
Discovered same issue happens in  the write draft. Not sure if its intentional or not.

**Comment by drewhoener** [comment]
Ways to reproduce? Is this the view you're talking about? Because I'm not getting any weird scrolling
![image](https://user-images.githubusercontent.com/6218989/79815344-84632800-834e-11ea-8c02-a1a0124f0c6c.png)

**Comment by atnguy** [comment]
I got it to partially flex
![image](https://user-images.githubusercontent.com/60637628/79816697-d2c5f600-8351-11ea-9fed-5c7c72ad7bc0.png)

but as you can see, the ssss won't flex

**Comment by drewhoener** [comment]
The expansion panels themselves are supposed to flex as well
If you set it from responsive to iphone or galaxy you can see it expands off of the page

![image](https://user-images.githubusercontent.com/6218989/79817556-bfb42580-8353-11ea-8f94-28dbe26bd1ff.png)

**Comment by atnguy** [comment]
I've gotten closer to fixing it by changing the width to 0 for the list style. 
![image](https://user-images.githubusercontent.com/60637628/79818298-749b1200-8355-11ea-9d8e-674b734696a3.png)

**Comment by atnguy** [comment]
I figured out where the issue is coming from: you get this when the width is equal to '100%'
`    list: {
        width: '100%',
    },`
![image](https://user-images.githubusercontent.com/60637628/79818626-3eaa5d80-8356-11ea-87cd-91027deef0a4.png)

You'll get this when the width is set to 0
`    list: {
        width: 0,
    },`

![image](https://user-images.githubusercontent.com/60637628/79818713-774a3700-8356-11ea-94c7-f287019d838b.png)

adding flexWrap and flex:1 will get you the image in my last comment
`    list: {
        width: 0,
        flex:1,
        flexWrap: 'wrap'
    },`

**Comment by drewhoener** [comment]
the buttons should be able to flex onto the next line probably
You  can probably get that done with wrapping the buttons with an element that's allowed to flex into the next row

**Comment by atnguy** [comment]
![image](https://user-images.githubusercontent.com/60637628/79819214-82ea2d80-8357-11ea-95d0-b92e6436930a.png)
Well I did get it to wrap, but it looks weird, like look at Sam's last name and the position of View and Download

**Comment by drewhoener** [comment]
has to be tested

**Comment by atnguy** [comment]
ok
